# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16OmN9sJN473jxxJxDGw5r9VNLWtQeQkY
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the merged dataset
df_baiku = pd.read_csv('https://raw.githubusercontent.com/allanbangkit/manabebaiku/main/dataset/baiku.csv')

# Define function to create visualizations

def plot_workingday_vs_cnt():
    plt.figure(figsize=(8, 6))
    sns.barplot(x='workingday_hour', y='cnt_hour', data=df_baiku, ci=None)
    plt.xlabel('Hari Libur (0) / Hari Kerja (1)')
    plt.ylabel('Jumlah Pengguna Sepeda (Rata-rata)')
    plt.title('Perbandingan Penggunaan Sepeda pada Hari Kerja dan Hari Libur')
    st.pyplot()

def plot_weather_vs_cnt():
    plt.figure(figsize=(8, 6))
    sns.barplot(x='weathersit_hour', y='cnt_hour', data=df_baiku, ci=None)
    plt.xlabel('Kondisi Cuaca (weathersit_hour)')
    plt.ylabel('Jumlah Pengguna Sepeda (cnt_hour)')
    plt.title('Hubungan Antara Kondisi Cuaca dan Jumlah Pengguna Sepeda')
    st.pyplot()

def plot_humidity_vs_cnt():
    plt.figure(figsize=(8, 6))
    sns.scatterplot(x='hum_day', y='cnt_day', data=df_baiku)
    plt.xlabel('Kelembaban Udara (hum_day)')
    plt.ylabel('Jumlah Pengguna Sepeda (cnt_day)')
    plt.title('Hubungan Antara Kelembaban Udara dan Jumlah Pengguna Sepeda')
    st.pyplot()

def plot_season_vs_cnt():
    plt.figure(figsize=(8, 6))
    sns.barplot(x='season', y='cnt_day', data=df_baiku, ci=None)
    plt.xlabel('Musim')
    plt.ylabel('Jumlah Pengguna Sepeda (Rata-rata)')
    plt.title('Perbandingan Penggunaan Sepeda Antara Musim')
    st.pyplot()

# Sidebar
st.sidebar.title('Menu')
selected_chart = st.sidebar.selectbox('Pilih Visualisasi:', ['Pertanyaan 1', 'Pertanyaan 2', 'Pertanyaan 3', 'Pertanyaan 4'])

# Main content
st.title('Dashboard Analisis Data Sepeda')

if selected_chart == 'Pertanyaan 1':
    plot_workingday_vs_cnt()
elif selected_chart == 'Pertanyaan 2':
    plot_weather_vs_cnt()
elif selected_chart == 'Pertanyaan 3':
    plot_humidity_vs_cnt()
elif selected_chart == 'Pertanyaan 4':
    plot_season_vs_cnt()